name: Lint & Unit Tests

on: push

jobs:
  Lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node version 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Run lint
        run: |
          npm install -g pnpm
          pnpm install
          pnpm lint
  Tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node version 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Run unit tests
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
          pnpm test
